== Kibi 5.4.3-2 and Kibana 5.4.3

[float]
=== Kibi Changes

Fixed: 

* Fixed issue where Kibi would not start when used with Elasticsearch 5.5.2 due to mapping loading problem  
* Kibi no longer use the `elasticsearch.plugins` configuration setting to store installed Elasticsearch plugin names
* Improved X-Pack security compatibility
* Improved migration from Kibi 4.6.x, where the sourceFiltering property was previously set for any index-pattern
* Improved migration from Kibi 4.6.x, where the pageSize parameter was previously incorrectly saved as string
* Various improvements in Sentinl see https://github.com/sirensolutions/sentinl/releases/tag/tag-5.5 for details

Changed:

* Update Siren Platform distributions to use Elasticsearch version 5.5.2
* Update Vanguard to version 5.5.2-1

Added: 

* Added ability to limit number of collected tuples per shard during the join operations
  This option can now be set globally via kibi:joinLimit in each relation's settings in the Relational Panel 

* Added support for dynamic object mapping type to Saved Object API 