== Kibi 0.3 and Kibana 4.4

[float]
=== Kibi Changes

* Using event times to create index names is no longer supported as of this release. Current versions of Elasticsearch include sophisticated date parsing APIs that Kibana uses to determine date information, removing the need to specify dates in the index pattern name.

[float]
=== Kibana Changes

[float]
[[enhancements]]
==== Enhancements

* {k4issue}1362[Issue 1362]: Color palette selector added.
* {k4issue}1553[Issue 1553]: Kibana can shorten URLs for shared or embedded items.
* {k4issue}5733[Issue 5733]: Time-based index pattern expansion can be set at index pattern creation time.
* {k4issue}5775[Issue 5775]: Adds a configuration option to change the maximum payload size sent to the server.
* {k4issue}4966[Issue 4966]: Logo is now in SVG format.
* {k4issue}3625[Issue 3625]: Downloaded visualizations now use the visualization name as the filename.
* {k4issue}5279[Issue 5279]: Large strings are truncated with an ellipsis (...).
* {k4issue}5241[Issue 5241]: Truncated visualization names are displayed in full as tooltips.
