[[targz]]
=== Install Kibi with `.tar.gz`

tar.gz packages can be downloaded from the {download-ref}[download page];
the demo versions contain a pre-configured Elasticsearch cluster in addition to
Kibi.

[[targz-running]]
==== Running Kibi from the command line

Kibi can be started from the command line as follows:

[source,sh]
--------------------------------------------
./bin/kibi
--------------------------------------------

By default, Kibi runs in the foreground, prints its logs to the
standard output (`stdout`), and can be stopped by pressing `Ctrl-C`.

[[targz-configuring]]
==== Configuring Kibi via config file

Kibi loads its configuration from the `config/kibi.yml`
file by default.  The format of this config file is explained in
<<settings>>.

[[targz-layout]]
==== Directory layout of `.tar.gz` archives

The `.tar.gz` packages are entirely self-contained.

This is very convenient because you don't have to create any directories to
start using Kibi, and uninstalling is as easy as removing the directory.
However, it is advisable to change the default locations of the config and data
directories so that you do not delete important data later on.


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | Kibi home directory or `$KIBI_HOME`
 d| Directory created by unpacking the archive; in demo distributions,
    the directory is `kibi`.
 d|

| bin
  | Binary scripts including `kibi` to start the Kibi server
    and `kibi-plugin` to install plugins
  | $KIBI_HOME\bin
 d|

| config
  | Configuration files including `kibi.yml`
  | $KIBI\config
 d|

| data
  | The location of the data files written to disk by Kibi and its plugins
  | $KIBI_HOME\data
 d|

| optimize
  | Transpiled source code. Certain administrative actions (e.g. plugin install)
    result in the source code being retranspiled on the fly.
  | $KIBI\optimize
 d|

| plugins
  | Plugin files location. Each plugin will be contained in a subdirectory.
  | $KIBI\plugins
 d|

|=======================================================================
