[[windows]]
=== Install {kibi-name} on Windows

{kibi-name} can be installed on Windows using the `.zip` package;
zip packages can be downloaded from the {download-ref}[download page].
The demo versions contain a pre-configured Elasticsearch cluster in addition to
{kibi-name}.

[[windows-running]]
==== Running {kibi-name} from the Command Line

{kibi-name} can be started from the command line as follows:

[source,sh]
--------------------------------------------
.\bin\investigate
--------------------------------------------

By default, {kibi-name} runs in the foreground, prints its logs to `STDOUT`,
and can be stopped by pressing `Ctrl-C`.

[[windows-configuring]]
==== Configuring {kibi-name} via Config File

{kibi-name} loads its configuration from the `$INVESTIGATE_HOME/config/investigate.yml`
file by default. The format of this config file is explained in
<<settings>>.

[[windows-layout]]
==== Directory Layout of `.zip` Archive

The `.zip` package is entirely self-contained.

This is very convenient because you do not have to create any directories to
start using {kibi-name}, and uninstalling {kibi-name} is as easy as removing the directory.
However, it is advisable to change the default locations of the config and data
directories so that you do not delete important data later on.


[cols="<h,<,<m,<m",options="header",]
|=======================================================================
| Type | Description | Default Location | Setting
| home
  | {kibi-name} home directory or `%INVESTIGATE_HOME%`
 d| Directory created by unpacking the archive; in demo distributions, the
    directory is `kibi`.
 d|

| bin
  | Binary scripts including `kibi` to start the {kibi-name} server
    and `kibi-plugin` to install plugins
  | %INVESTIGATE_HOME%\bin
 d|

| config
  | Configuration files including `investigate.yml`
  | %INVESTIGATE_HOME%\config
 d|

| data
  | The location of the data files written to disk by {kibi-name} and its plugins
  | %INVESTIGATE_HOME%\data
 d|

| optimize
  | Transpiled source code. Certain administrative actions, e.g., `plugin install`,
    result in the source code being retranspiled on the fly.
  | %INVESTIGATE_HOME%\optimize
 d|

| plugins
  | The location of the plugin files. Each plugin will be contained in a subdirectory.
  | %INVESTIGATE_HOME%\plugins
 d|

|=======================================================================
