[[cross_frame_communication]]
= Cross frame communication [Enterprise Edition only]

To allow cross frame communication Kibi exposes an object at **window.kibi**;
the object can be called only if both Kibi and the container page are in the same domain.

[float]
== Methods

`generateShortUrl(shareAsEmbed, displayNavBar)`

Generates a shortened URL containing the current Kibi state and returns
a promise fulfilled with the URL.

**Parameters**:

- `shareAsEmbed`: if set to true, the top navigation bar and dashboard tabs will be hidden when opening the shortened URL.
- `displayNavBar`: if set to true, the dashboard tabs will not be hidden when `sharedAsEmbed` is set to true.

**Sample usage**:

Put the following code in the container page, replacing `kibiframe` with
the ID of the frame in which Kibi is embedded:

```
document.getElementById('kibiframe')
.contentWindow
.kibi
.generateShortUrl(true, true)
.then(function(url) {
  console.log("Generated URL: " + url);
})
.catch(function(error) {
  console.log("An error occurred while generating the URL");
});

```

If possible, it is recommended to purge old documents of type `url` from the `.kibi`
index periodically; old documents can be identified by looking at the `createDate` attribute.
