[[introduction]]
== Introduction

Kibi is an open source data intelligence platform built upon
{kibana-announcement}[Kibana {kibana-version}].

Kibi allows to perform complex analytics on large volumes of data by providing
customizable visualizations (charts, maps, metrics and tables) on Elasticsearch
queries; visualizations can be organized into multiple dashboards, presented
in a tabbed user interface.

Elasticsearch results can be filtered and augmented by queries on multiple
external datasources such as SQL databases and triplestores; queries on
external datasources can also be used as aggregations in visualizations.

In addition to standard Kibana visualizations, Kibi provides:

- The <<relational-filter, Relational Filter>> visualization, which allows
to configure relations between fields in different indices and apply
cross-dashboard filters (pivoting).

- The <<relational-panel, Relational Panel>>, which defines relations between indices by specifying on which fields to join. This enables to browse dashboards as a **connected** set, where filtering one dashboards updates results from the other dashboards.

- The <<wordcloud,Kibi Word Cloud>> visualization, which displays a cloud of
high frequency terms from the documents returned by an Elasticsearch query.

- The <<timeline,Kibi Timeline>> visualization, which displays a timeline
with multiple groups of data coming from different indices.

- The <<radar-chart,Radar Chart>> visualization, which is a https://en.wikipedia.org/wiki/Radar_chart[graphical method] for displaying multivarate data.
with multiple groups of data coming from different indices.

- The <<enhanced-search-results,Enhanced search results>> visualization, which
displays query results in a table.

- The <<templated-query-viewer,Templated Query Viewer>>, which enables the
visualization of queries on external datasource through Jade or Handlebars
templates.

The Relational Filter visualization requires the {siren-join-website}[Siren Join plugin {siren-join-version}] for
Elasticsearch. The plugin is compatible with Elasticsearch {siren-join-version}.

[float]
=== How does Kibi compare to Kibana?

Kibi is currently developed as a fork of Kibana {kibana-version}. The plugin API of https://www.elastic.co/blog/kibana-4-3-1-and-4-2-2-and-4-1-4[Kibana 4.2.x] allows us to keep the amount of forked code to a minimum, but as the API is currently in development, a fork is still needed.

=== What's new in Kibi v{kibi-version}

This new version of Kibi provides many improvements and new features, the main one are listed below:

- Kibi is merged with {kibana-announcement}[Kibana {kibana-version}] which introduced a major refactoring of the code.
- A new <<radar-chart,radar chart>> visualisation.
