[[production]]
== Using Kibi in a Production Environment

Please read the https://www.elastic.co/guide/en/kibana/4.4/production.html[Kibana in Production]
section in the Kibana manual for production best practices, especially
the *Controlling access* section.

NOTE: From v4.4.1 Kibi Enterprise Edition comes with full Shield integration.
Shield provides fine grained user access control at the index, document and field levels.

Make sure to set the configuration file as readable only to the user running
the Kibi process as it may contain credentials in the database connection
strings.

We also recommend to create a database user without write privileges
as they are not required by the system.

To prevent data loss it is a good practice to restrict access to the
elasticsearch cluster. Below is a simple nginx configuration to do it.

```
events {
  worker_connections  1024;
}
http {
  upstream elasticsearch {
    server 127.0.0.1:9200;
  }
  server {
    listen 8080;
    auth_basic "Protected Elasticsearch";
    auth_basic_user_file passwords;
    location / {
      proxy_pass http://elasticsearch;
      proxy_redirect off;
    }
  }
}
```

For more information about nginx configuration visit https://www.elastic.co/blog/playing-http-tricks-nginx[Playing HTTP Tricks with Nginx]
