[[setup]]
= Set Up Kibi

[partintro]
--
This section includes information on how to setup Kibi and get it running,
including:

* Downloading
* Installing
* Starting
* Configuring
* Upgrading

[[supported-platforms]]
[float]
== Supported platforms

Packages of Kibi are provided for and tested against Linux, Mac OS and
Windows. Since Kibi runs on Node.js, we include the necessary Node.js
binaries for these platforms. Running Kibi against a separately maintained
version of Node.js is not supported.

[float]
[[elasticsearch-version]]
== Elasticsearch version

Kibi should be configured to run against an Elasticsearch node of the same
version. This is the officially supported configuration.

Running different major version releases of Kibi and Elasticsearch (e.g.
Kibi 5.x and Elasticsearch 2.x) is not supported, nor is running a minor
version of Kibi that is newer than the version of Elasticsearch (e.g. Kibi
5.4 and Elasticsearch 5.0).

Running a minor version of Elasticsearch that is higher than Kibi will
generally work in order to facilitate an upgrade process where Elasticsearch
is upgraded first (e.g. Kibi 5.2.2 and Elasticsearch 5.4). In this
configuration, a warning will be logged on Kibi server startup, so it's only
meant to be temporary until Kibi is upgraded to the same version as
Elasticsearch.

Running different patch version releases of Kibi and Elasticsearch (e.g.  Kibi
5.4.1-1 and Elasticsearch 5.4) is generally supported, though we encourage
users to run the same versions of Kibi and Elasticsearch down to the patch
version.
--

include::setup/install.asciidoc[]

include::setup/settings.asciidoc[]

include::setup/access.asciidoc[]

include::setup/connect-to-elasticsearch.asciidoc[]

include::setup/tribe.asciidoc[]

include::setup/production.asciidoc[]

include::setup/upgrade.asciidoc[]
