[[upgrade]]
== Upgrading from a previous version

An existing Kibi installation can be upgraded as follows:

- backup the `.kibi` index.
- {elastic-ref}setup-upgrade.html[upgrade Elasticsearch]; before restarting each node, make sure to install a compatible version of the
  {siren-join-website}#compatibility[SIREn Join] plugin.
- download and setup the new Kibi version, then upgrade third party Kibi/Kibana plugins.
- execute the <<kibi-upgrade-command, upgrade command>>.

[float]
=== Backing up the .kibi index.

Before upgrading it is strongly recommended to have a backup of the `.kibi` index; the recommended way to perform regular backups of
Elasticsearch indexes is through the {elastic-ref}modules-snapshots.html[snapshot and restore modules].

A useful tool to take a one-off backup is https://www.npmjs.com/package/elasticdump[elasticdump]; once installed, it is possible to dump
the `.kibi` index mappings and data on two separate files by running the following commands:

[source]
----
elasticdump --input=http://<cluster address>:<cluster port>/<kibi index> --type=mapping --output=<mappings_dump_file>

elasticdump --input=http://<cluster address>:<cluster port>/<kibi index> --type=data --output=<data_dump_file>
----

Full example:

[source,shell]
----
$ elasticdump --input=http://192.168.99.100:9200/.kibi --type=mapping --output=mappings.json
$ elasticdump --input=http://192.168.99.100:9200/.kibi --type=data --output=data.json
----

If needed, you can restore the index from dumps by running the following commands:

[source]
----
elasticdump --input=<mappings_dump_file> --type=mapping --output=http://<cluster address>:<cluster port>/<kibi index>

elasticdump --input=<data_file> --type=data --output=http://<cluster address>:<cluster port>/<kibi index>
----

Full example:

[source,shell]
----
$ elasticdump --input=mappings.json --type=mapping --output=http://192.168.99.100:9200/.kibi
$ elasticdump --input=data.json --type=data --output=http://192.168.99.100:9200/.kibi
----

[float]
[[kibi-upgrade-command]]
=== Upgrading the .kibi index.

To upgrade the objects in the `.kibi` index (dashboards, visualizations, etc.), move to the directory in which Kibi is installed and
execute the following command:

[source,shell]
----
bin/kibi upgrade
----

The command will look for out of date objects and upgrade them, e.g.:

[source,shell]
----
$ bin/kibi upgrade
  log   [17:58:33.494] [info][status][plugin:elasticsearch] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [17:58:36.127] [info][migrations] Executing migration "Upgrade scripts from version 1 to version 2"
  log   [17:58:36.141] [info][migrations] Executed migration "Upgrade scripts from version 1 to version 2"
  log   [17:58:36.142] [info][migrations] Executing migration "Upgrade kibi graph browser visualization to version 2."
  log   [17:58:36.157] [info][migrations] Executed migration "Upgrade kibi graph browser visualization to version 2."
  log   [17:58:36.158] [info][migrations] Executing migration "Upgrade saved queries from version 1 to version 2"
  log   [17:58:36.242] [info][migrations] Executed migration "Upgrade saved queries from version 1 to version 2"
  log   [17:58:36.242] [info][migrations] Executing migration "Upgrade saved templates from version 1 to version 2"
  log   [17:58:36.303] [info][migrations] Executed migration "Upgrade saved templates from version 1 to version 2"
  log   [17:58:36.303] [info][migrations] Executing migration "Upgrade saved queries definitions in external query terms aggregation, enhanced search results and query viewer."
  log   [17:58:36.400] [info][migrations] Executed migration "Upgrade saved queries definitions in external query terms aggregation, enhanced search results and query viewer."
Upgraded 20 objects.
----

It is possible to run the command multiple times, however running the command at the same time from multiple machines is not supported.
